version: "3.2"
services:
  nodejs:
    build: ./app
    image: amakundu/nodejs-mysql-app
    networks:
      - frontend
      - backend
    volumes:
      - ./app/:/dev_app
      - /dev_app/node_modules
    ports:
      - "6710:8005"
    container_name: kata-app
  mysql:
    image: mysql:latest
    hostname: mysql
    cap_add:
      - SYS_NICE  
    env_file: ./app/.env
    networks:
      - backend
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6720:3306"
    container_name: kata-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "6730:80"
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql
    volumes:
      - /sessions
    container_name: kata-phpmyadmin
networks:
  frontend:
  backend: